version: "3.4"
services:
  lighthouse_beacon:
    image: parithoshj/lighthouse:merge-mainnetconfig-09a5d62
    container_name: lighthouse_beacon
    volumes:
      - ./beacon_data:/consensus_data
      - ./custom_config_data:/custom_config_data
    command: >
      lighthouse --debug-level=info --datadir=/consensus_data --testnet-dir=/custom_config_data bn --disable-enr-auto-update --enr-address=$IP_ADDRESS --enr-udp-port 9000 --enr-tcp-port 9000 --dummy-eth1 --boot-nodes=$ENR --http --http-port=4000 --merge --http-allow-sync-stalled --disable-packet-filter --execution-endpoints=http://127.0.0.1:8545 --terminal-total-difficulty-override=$TOTAL_TERMINAL_DIFFICULTY
    network_mode: host
  lighthouse_validator:
    image: parithoshj/lighthouse:merge-mainnetconfig-09a5d62
    container_name: lighthouse_validator
    volumes:
      - ./custom_config_data:/custom_config_data
      - ./validator_keys:/validator_keys
    command: >
      lighthouse --testnet-dir="/custom_config_data" vc --validators-dir="/validator_keys/validators" --secrets-dir="/validator_keys/secrets" --init-slashing-protection --server=http://127.0.0.1:4000 --graffiti="hi mom" --http --http-port=4002
    network_mode: host