version: "3.4"
services:
  geth_init:
    image: ethpandaops/geth:4844-devnet-6-990e113
    container_name: geth_init
    volumes:
      - ./execution_data:/execution_data
      - ./custom_config_data:/custom_config_data
    command: >
      --datadir=/execution_data init /custom_config_data/genesis.json
    network_mode: host
  geth:
    image: ethpandaops/geth:4844-devnet-6-990e113
    container_name: geth
    restart: on-failure
    depends_on:
      - geth_init
    volumes:
      - ./execution_data:/execution_data
      - ./custom_config_data:/custom_config_data
    command: >
      --datadir=/execution_data --networkid=$NETWORK_ID --syncmode=full --http --http.vhosts=* --http.api "eth,net,web3,debug,admin" --authrpc.addr=0.0.0.0 --authrpc.port=8551 --networkid=$NETWORK_ID --authrpc.vhosts=* --authrpc.jwtsecret=/custom_config_data/auth.jwt --nat extip:$IP_ADDRESS --bootnodes=$ENODE
    network_mode: host